# Generated by Django 4.1.4 on 2022-12-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='playByPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yardsFromEndzone', models.SmallIntegerField(blank=True, null=True)),
                ('turnover', models.BooleanField()),
                ('scoringPlay', models.BooleanField()),
                ('offenseScored', models.BooleanField(blank=True, null=True)),
                ('pointsScored', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='playerMatchOffense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='playerWeekStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
