# Generated by Django 4.1.4 on 2022-12-20 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0002_playbyplay_player_playermatchoffense_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nflMatch',
        ),
        migrations.DeleteModel(
            name='playByPlay',
        ),
        migrations.DeleteModel(
            name='playerMatchOffense',
        ),
        migrations.DeleteModel(
            name='playerWeekStatus',
        ),
        migrations.AddField(
            model_name='nflteam',
            name='abbreviation',
            field=models.CharField(default='-', max_length=3),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='division',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='endYear',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='fullName',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='geography',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='orgId',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='startYear',
            field=models.SmallIntegerField(default=2002, validators=[django.core.validators.MinValueValidator(2002)]),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='teamName',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='firstSeason',
            field=models.SmallIntegerField(default='2000'),
        ),
        migrations.AddField(
            model_name='player',
            name='lastSeason',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='-', max_length=60),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfl_db.nflteam'),
        ),
    ]
