# Generated by Django 4.1.4 on 2022-12-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0004_playerweekstatus_nflmatch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nflMatch',
            new_name='nflMatches',
        ),
    ]
