# Generated by Django 4.1.4 on 2022-12-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0008_remove_nflmatch_awayteamdefensepointsscored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflmatch',
            name='neutralStadium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='overtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='playoffs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='preseason',
            field=models.BooleanField(default=False),
        ),
    ]
