# Generated by Django 4.1.4 on 2022-12-20 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0009_nflmatch_neutralstadium_nflmatch_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflmatch',
            name='yearOfSeason',
            field=models.SmallIntegerField(default=2002, validators=[django.core.validators.MinValueValidator(2002)]),
        ),
    ]
