# Generated by Django 4.1.4 on 2022-12-20 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0010_nflmatch_yearofseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflmatch',
            name='weekOfSeason',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-4), django.core.validators.MaxValueValidator(22)]),
        ),
    ]
