# Generated by Django 4.1.4 on 2022-12-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0011_nflmatch_weekofseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamDefensePointsScored',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamExplosivePlays',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamFGAllowed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamFGScored',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamGiveaways',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamPoints',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamPointsAllowed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamReceivingTDAllowed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamReceivingTDScored',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamReceivingYards',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamReceivingYardsAllowed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamRushYardsAllowed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamRushingTDAllowed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamRushingTDScored',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamRushingYards',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamSpecialTeamsPointsScored',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamTakeaways',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamTotalYards',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamYardsAllowed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
