# Generated by Django 4.1.4 on 2022-12-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0018_alter_nflteam_orgid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflmatch',
            old_name='awayTeamScore',
            new_name='awayTeamPoints',
        ),
        migrations.RenameField(
            model_name='nflmatch',
            old_name='awayTeamRushingYarsds',
            new_name='awayTeamRushingYards',
        ),
        migrations.RenameField(
            model_name='nflteam',
            old_name='orgId',
            new_name='espnId',
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='awayTeamPointsAllowed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='espnId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
