# Generated by Django 4.1.4 on 2022-12-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0019_rename_awayteamscore_nflmatch_awayteampoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflmatch',
            name='espnId',
            field=models.IntegerField(unique=True),
        ),
    ]
