# Generated by Django 4.1.4 on 2022-12-22 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0021_teammatchperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatchperformance',
            name='weekOfSeason',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-4), django.core.validators.MaxValueValidator(22)]),
        ),
        migrations.AddField(
            model_name='teammatchperformance',
            name='yearOfSeason',
            field=models.SmallIntegerField(default=2002, validators=[django.core.validators.MinValueValidator(2002)]),
        ),
    ]
