# Generated by Django 4.1.4 on 2022-12-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0023_nflmatch_indoorstadium_nflmatch_precipitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatchperformance',
            name='teamEspnId',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammatchperformance',
            name='totalPassYardsAllowed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammatchperformance',
            name='totalPointsAllowed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammatchperformance',
            name='totalRushYardsAllowed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammatchperformance',
            name='totalYardsAllowedByDefense',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='teammatchperformance',
            constraint=models.UniqueConstraint(fields=('matchEspnId', 'teamEspnId'), name='UniqueTeamsPerMatch'),
        ),
    ]
