# Generated by Django 4.1.4 on 2022-12-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0024_teammatchperformance_teamespnid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflmatch',
            name='awayTeamEspnId',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamEspnId',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammatchperformance',
            name='atHome',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
