# Generated by Django 4.1.4 on 2022-12-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0025_nflmatch_awayteamespnid_nflmatch_hometeamespnid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatchperformance',
            name='totalPointsAllowedByDefense',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
