# Generated by Django 4.1.4 on 2022-12-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0027_rename_matchline_nflmatch_matchlinehometeam'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflmatch',
            name='awayTeamMoneyLine',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='homeTeamMoneyLine',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
