# Generated by Django 4.1.4 on 2023-01-03 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0028_nflmatch_awayteammoneyline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammatchperformance',
            old_name='passPlaysTwentyPlus',
            new_name='passPlaysTwentyFivePlus',
        ),
    ]
