# Generated by Django 4.1.4 on 2023-01-19 05:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0029_rename_passplaystwentyplus_teammatchperformance_passplaystwentyfiveplus'),
    ]

    operations = [
        migrations.CreateModel(
            name='driveOfPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSpanOfDrive', models.DurationField(blank=True, null=True)),
                ('driveResult', models.SmallIntegerField(choices=[(1, 'TOUCHDOWN'), (2, 'FIELD GOAL MADE'), (3, 'FIELD GOAL MISSED'), (4, 'PUNT'), (5, 'PUNT BLOCKED'), (6, 'INTERCEPTION'), (7, 'INTERCEPTION RETURNED FOR TOUCHDOWN'), (8, 'FUMBLE LOST'), (9, 'FUMBLE LOST RETURNED FOR TOUCHDOWN'), (10, 'OFFENSE RECOVERED FUMBLE FOR TOUCHDOWN'), (11, 'TURNOVER ON DOWNS'), (12, 'END OF FIRST HALF'), (13, 'END OF SECOND HALF'), (14, 'END OF OVERTIME')], default=4)),
                ('startOfDriveYardLine', models.SmallIntegerField(blank=True, null=True)),
                ('endOfDriveYardLine', models.SmallIntegerField(blank=True, null=True)),
                ('numberOffensivePlays', models.SmallIntegerField(blank=True, null=True)),
                ('timeElapsedInSeconds', models.SmallIntegerField(blank=True, null=True)),
                ('reachedRedZone', models.BooleanField()),
                ('nflMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_db.nflmatch')),
                ('teamOnOffense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_db.nflteam')),
            ],
        ),
        migrations.CreateModel(
            name='playByPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playType', models.SmallIntegerField(choices=[(1, 'RUSH'), (2, 'COMPLETED PASS'), (3, 'INCOMPLETE PASS'), (4, 'SACK'), (5, 'INTERCEPTION'), (6, 'INTERCEPTION RETURN TOUCHDOWN'), (7, 'OFFENSIVE FUMBLE RECOVERY'), (8, 'OFFENSIVE FUMBLE RECOVERY TOUCHDOWN'), (9, 'DEFENSIVE FUMBLE RECOVERY'), (10, 'DEFENSIVE FUMBLE RECOVERY TOUCHDOWN'), (11, 'PUNT'), (12, 'PUNT BLOCKED'), (13, 'PUNT MUFFED PUNTING TEAM RECOVERY'), (14, 'PUNT MUFFED RECEIVING TEAM RECOVERY'), (15, 'FG KICK'), (16, 'FG KICK MISSED'), (17, 'KICKOFF'), (18, 'KICKOFF RECOVERY KICKING TEAM'), (19, 'PAT KICK MADE'), (20, 'PAT KICK MISSED'), (21, '2PT CONVERSION'), (22, 'KNEEL'), (23, 'SPIKE'), (24, 'NO PLAY/BLOWN DEAD'), (25, 'TIMEOUT')], default=1)),
                ('yardsFromEndzone', models.SmallIntegerField(blank=True, null=True)),
                ('yardsOnPlay', models.SmallIntegerField(blank=True, null=True)),
                ('playDown', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('turnover', models.BooleanField()),
                ('penaltyOnPlay', models.BooleanField()),
                ('penaltyIsOnOffense', models.BooleanField(blank=True, null=True)),
                ('yardsGainedOrLostOnPenalty', models.SmallIntegerField(blank=True, null=True)),
                ('scoringPlay', models.BooleanField()),
                ('offenseScored', models.BooleanField(blank=True, null=True)),
                ('pointsScored', models.SmallIntegerField(blank=True, null=True)),
                ('nflMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_db.nflmatch')),
                ('teamOnOffense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_db.nflteam')),
            ],
        ),
        migrations.DeleteModel(
            name='player',
        ),
    ]
