# Generated by Django 4.1.4 on 2023-01-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0030_driveofplay_playbyplay_delete_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='playByPlay',
        ),
    ]
