# Generated by Django 4.1.4 on 2023-01-19 05:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0031_delete_playbyplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='playByPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playType', models.SmallIntegerField(choices=[(1, 'RUSH'), (2, 'COMPLETED PASS'), (3, 'INCOMPLETE PASS'), (4, 'SACK'), (5, 'INTERCEPTION'), (6, 'INTERCEPTION RETURN TOUCHDOWN'), (7, 'OFFENSIVE FUMBLE RECOVERY'), (8, 'OFFENSIVE FUMBLE RECOVERY TOUCHDOWN'), (9, 'DEFENSIVE FUMBLE RECOVERY'), (10, 'DEFENSIVE FUMBLE RECOVERY TOUCHDOWN'), (11, 'PUNT'), (12, 'PUNT BLOCKED'), (13, 'PUNT MUFFED PUNTING TEAM RECOVERY'), (14, 'PUNT MUFFED RECEIVING TEAM RECOVERY'), (15, 'FG KICK'), (16, 'FG KICK MISSED'), (17, 'KICKOFF'), (18, 'KICKOFF RECOVERY KICKING TEAM'), (19, 'PAT KICK MADE'), (20, 'PAT KICK MISSED'), (21, '2PT CONVERSION'), (22, 'KNEEL'), (23, 'SPIKE'), (24, 'NO PLAY/BLOWN DEAD'), (25, 'TIMEOUT')], default=1)),
                ('yardsFromEndzone', models.SmallIntegerField(blank=True, null=True)),
                ('yardsOnPlay', models.SmallIntegerField(blank=True, null=True)),
                ('playDown', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('turnover', models.BooleanField()),
                ('penaltyOnPlay', models.BooleanField()),
                ('penaltyIsOnOffense', models.BooleanField(blank=True, null=True)),
                ('yardsGainedOrLostOnPenalty', models.SmallIntegerField(blank=True, null=True)),
                ('scoringPlay', models.BooleanField()),
                ('offenseScored', models.BooleanField(blank=True, null=True)),
                ('pointsScored', models.SmallIntegerField(blank=True, null=True)),
                ('nflMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_db.nflmatch')),
                ('teamOnOffense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_db.nflteam')),
            ],
        ),
    ]
