# Generated by Django 4.1.4 on 2023-01-19 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0033_delete_driveofplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='driveOfPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSpanOfDrive', models.DurationField(blank=True, null=True)),
                ('driveResult', models.SmallIntegerField(choices=[(1, 'TOUCHDOWN'), (2, 'FIELD GOAL MADE'), (3, 'FIELD GOAL MISSED'), (4, 'PUNT'), (5, 'PUNT BLOCKED'), (6, 'INTERCEPTION'), (7, 'INTERCEPTION RETURNED FOR TOUCHDOWN'), (8, 'FUMBLE LOST'), (9, 'FUMBLE LOST RETURNED FOR TOUCHDOWN'), (10, 'OFFENSE RECOVERED FUMBLE FOR TOUCHDOWN'), (11, 'TURNOVER ON DOWNS'), (12, 'END OF FIRST HALF'), (13, 'END OF SECOND HALF'), (14, 'END OF OVERTIME')], default=4)),
                ('startOfDriveYardLine', models.SmallIntegerField(blank=True, null=True)),
                ('endOfDriveYardLine', models.SmallIntegerField(blank=True, null=True)),
                ('numberOffensivePlays', models.SmallIntegerField(blank=True, null=True)),
                ('timeElapsedInSeconds', models.SmallIntegerField(blank=True, null=True)),
                ('reachedRedZone', models.BooleanField()),
                ('nflMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_db.nflmatch')),
                ('teamOnOffense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_db.nflteam')),
            ],
        ),
    ]
