# Generated by Django 4.1.4 on 2023-01-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0034_driveofplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveofplay',
            name='espnId',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driveofplay',
            name='sequenceNumber',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='driveOfPlay',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nfl_db.driveofplay'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playbyplay',
            name='espnId',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driveofplay',
            name='driveResult',
            field=models.SmallIntegerField(choices=[(1, 'TOUCHDOWN'), (2, 'FIELD GOAL MADE'), (3, 'FIELD GOAL MISSED'), (4, 'PUNT'), (5, 'PUNT BLOCKED'), (6, 'PUNT BLOCKED TD'), (7, 'INTERCEPTION'), (8, 'INTERCEPTION RETURNED FOR TOUCHDOWN'), (9, 'FUMBLE LOST'), (10, 'FUMBLE LOST RETURNED FOR TOUCHDOWN'), (11, 'OFFENSE RECOVERED FUMBLE FOR TOUCHDOWN'), (12, 'TURNOVER ON DOWNS'), (13, 'END OF HALF'), (14, 'END OF SECOND HALF'), (15, 'END OF OVERTIME'), (16, 'SAFETY')], default=4),
        ),
        migrations.AlterField(
            model_name='playbyplay',
            name='playType',
            field=models.SmallIntegerField(choices=[(1, 'RUSH'), (2, 'COMPLETED PASS'), (3, 'INCOMPLETE PASS'), (4, 'SACK'), (5, 'INTERCEPTION'), (6, 'INTERCEPTION RETURN TOUCHDOWN'), (7, 'OFFENSIVE FUMBLE RECOVERY'), (8, 'OFFENSIVE FUMBLE RECOVERY TOUCHDOWN'), (9, 'DEFENSIVE FUMBLE RECOVERY'), (10, 'DEFENSIVE FUMBLE RECOVERY TOUCHDOWN'), (11, 'SAFETY'), (12, 'PUNT'), (13, 'PUNT BLOCKED'), (14, 'PUNT MUFFED PUNTING TEAM RECOVERY'), (15, 'PUNT MUFFED RECEIVING TEAM RECOVERY'), (16, 'FG KICK'), (17, 'FG KICK MISSED'), (18, 'KICKOFF'), (19, 'KICKOFF RECOVERY KICKING TEAM'), (20, 'PAT KICK MADE'), (21, 'PAT KICK MISSED'), (22, '2PT CONVERSION SUCCESS RUSH'), (23, '2PT CONVERSION SUCCESS PASS'), (24, '2PT CONVERSION FAILED RUSH'), (25, '2PT CONVERSION FAILED PASS'), (26, '2PT CONVERSION SUCCESS OTHER'), (27, '2PT CONVERSION FAILED OTHER'), (28, 'KNEEL'), (29, 'SPIKE'), (30, 'NO PLAY/BLOWN DEAD'), (31, 'TIMEOUT')], default=1),
        ),
    ]
