# Generated by Django 4.1.4 on 2023-01-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_db', '0035_driveofplay_espnid_driveofplay_sequencenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammatchperformance',
            old_name='redZoneTDConversionPct',
            new_name='redZoneTDConversions',
        ),
        migrations.AlterField(
            model_name='driveofplay',
            name='driveResult',
            field=models.SmallIntegerField(choices=[(1, 'TOUCHDOWN'), (2, 'FIELD GOAL MADE'), (3, 'FIELD GOAL MISSED'), (4, 'PUNT'), (5, 'PUNT BLOCKED'), (6, 'PUNT BLOCKED TD'), (7, 'INTERCEPTION'), (8, 'INTERCEPTION RETURNED FOR TOUCHDOWN'), (9, 'FUMBLE LOST'), (10, 'FUMBLE LOST RETURNED FOR TOUCHDOWN'), (11, 'OFFENSE RECOVERED FUMBLE FOR TOUCHDOWN'), (12, 'TURNOVER ON DOWNS'), (13, 'END OF HALF'), (14, 'END OF SECOND HALF'), (15, 'END OF OVERTIME'), (16, 'SAFETY'), (17, 'OTHER')], default=4),
        ),
    ]
